create extension if not exists pgcrypto;

create table if not exists public.app_settings (
  key text primary key,
  value text not null,
  updated_at timestamptz not null default timezone('utc', now())
);

insert into public.app_settings (key, value)
values ('admin_password_hash', crypt('xw2d', gen_salt('bf')))
on conflict (key) do nothing;

create table if not exists public.locations (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default timezone('utc', now())
);

insert into public.locations (name)
values ('上层'), ('中层'), ('下层'), ('侧面')
on conflict (name) do nothing;

create table if not exists public.packages (
  id uuid primary key default gen_random_uuid(),
  tracking_number text not null unique,
  package_date date not null default current_date,
  location text not null,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_packages_created_at on public.packages (created_at desc);
create index if not exists idx_packages_date on public.packages (package_date desc);

alter table public.locations enable row level security;
alter table public.packages enable row level security;

drop policy if exists "anon_can_read_locations" on public.locations;
create policy "anon_can_read_locations"
on public.locations
for select
to anon, authenticated
using (true);

drop policy if exists "anon_can_read_packages" on public.packages;
create policy "anon_can_read_packages"
on public.packages
for select
to anon, authenticated
using (true);

grant usage on schema public to anon, authenticated;
grant select on public.locations to anon, authenticated;
grant select on public.packages to anon, authenticated;

create or replace function public.admin_login(p_password text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  stored_hash text;
begin
  if coalesce(trim(p_password), '') = '' then
    return false;
  end if;

  select value
  into stored_hash
  from public.app_settings
  where key = 'admin_password_hash';

  if stored_hash is null then
    return false;
  end if;

  return stored_hash = crypt(p_password, stored_hash);
end;
$$;

grant execute on function public.admin_login(text) to anon, authenticated;

create or replace function public.insert_package_with_password(
  p_password text,
  p_tracking_number text,
  p_location text,
  p_package_date date default current_date
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_tracking text := btrim(coalesce(p_tracking_number, ''));
  v_location text := btrim(coalesce(p_location, ''));
  inserted_row public.packages%rowtype;
begin
  if not public.admin_login(p_password) then
    raise exception '录入密码错误';
  end if;

  if v_tracking = '' then
    raise exception '请填写快递单号';
  end if;

  if v_location = '' then
    raise exception '请选择位置';
  end if;

  insert into public.packages (tracking_number, package_date, location)
  values (v_tracking, coalesce(p_package_date, current_date), v_location)
  returning * into inserted_row;

  return jsonb_build_object(
    'success', true,
    'message', '录入成功',
    'trackingNumber', inserted_row.tracking_number,
    'date', inserted_row.package_date,
    'location', inserted_row.location,
    'createdAt', inserted_row.created_at
  );
exception
  when unique_violation then
    raise exception '单号 % 已存在，请勿重复录入', v_tracking;
end;
$$;

grant execute on function public.insert_package_with_password(text, text, text, date) to anon, authenticated;
